format = gauntpy-synthetic-maze-v1
name = pathological-slot-saturation
description = Nearly every playable cell contains a linked ghost MOB.
frames = 120
level = 16
seed = 0
character = elf
health = 20000
input = idle

[maze]
################################
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGEG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGG@GGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
################################
