# Generated by doc/generate_r2_loader.py; do not edit by hand.
o row9.bin 0x000000 r-x
o row10.bin 0x038000 r-x
o row76.bin 0x040000 r-x
e io.va=true
e anal.arch=m68k
e asm.arch=m68k
e asm.cpu=68010
e asm.bits=32
e cfg.bigendian=true
fs functions
af+ 0x0300 exception_handler
af+ 0x0314 irq1_handler
af+ 0x0326 irq2_handler
af+ 0x0338 irq3_handler
af+ 0x034a irq4_vblank_handler
af+ 0x036c irq6_handler
af+ 0x05e2 reset_entry
af+ 0x03a0 normal_boot
af+ 0x061e selftest_boot
af+ 0x070c main_init_cont
af+ 0xa2c mem_test_short
af+ 0xa6a mem_test_full
af+ 0xc52 display_working_ram_error
af+ 0x0c98 error_display_ram
af+ 0x0cc0 rom_checksum_display
af+ 0x0e14 os_vblank_mode_entry
af+ 0x0e5e os_vblank_handler
af+ 0x129a os_selftest_loop
af+ 0x2918 format_number
af+ 0x2a5e format_hex
af+ 0x2abe format_decimal
af+ 0x2e36 display_text
af+ 0x2f04 draw_string
af+ 0x2eb4 display_decimal_value
af+ 0x2eea display_hex_value
af+ 0x3044 write_alpha_char
af+ 0x2ce4 calc_alpha_address
af+ 0x3522 init_alpha_display
af+ 0x3586 write_alpha_word
af+ 0x3162 start_blink_text
af+ 0x3168 start_timed_text
af+ 0x316c start_progressive_text
af+ 0x3156 start_progressive_text_clear
af+ 0x3122 start_text_line_rotation
af+ 0x30f4 stop_text_effect
af+ 0x3130 init_fullscreen_text_scroll
af+ 0x2b3c process_text_effects
af+ 0x31d2 display_large_text
af+ 0x3346 clear_large_text
af+ 0x32bc display_large_char_at
af+ 0x32a0 display_large_char_raw
af+ 0x35b2 set_text_position
af+ 0x332a display_large_text_at
af+ 0x32da display_large_decimal_value
af+ 0x3310 display_large_hex_value
af+ 0x359a wait_vblanks
af+ 0x4184 send_sound_command
af+ 0x41fa process_sound
af+ 0x42c8 read_sound_data
af+ 0x427a sound_receive_irq_body
af+ 0x42f8 reset_sound_cpu
af+ 0x41c8 send_sound_command_wait
af+ 0x41cc try_send_sound_command
af+ 0x432e eeprom_process
af+ 0x44e8 eeprom_init
af+ 0x47a8 eeprom_request_write
af+ 0x4802 eeprom_check_busy
af+ 0x4822 eeprom_read_block
af+ 0x35c4 process_coins
af+ 0x3706 get_coin_multiplier
af+ 0x3740 calc_health_per_coin
af+ 0x37c2 check_and_deduct_coin
af+ 0x3804 check_and_deduct_credits
af+ 0x3860 read_eeprom_setting
af+ 0x38c0 read_game_config
af+ 0x39b0 read_high_score_entry
af+ 0x3a7e write_high_score_entry
af+ 0x3be8 update_active_player_time_stats
af+ 0x3cf6 write_eeprom_setting
af+ 0x3f68 rank_high_score
af+ 0x401a activate_player_time_tracking
af+ 0x4038 record_player_session_histogram
af+ 0x5454 run_statistics_screens
af+ 0x58c6 run_game_options
af+ 0x1632 display_init_clear
af+ 0x17d4 run_alpha_test
af+ 0xfca run_color_test
af+ 0x1b20 run_motion_object_test
af+ 0x21a0 validate_game_rom
af+ 0x03b6 normal_boot_spare_test_done
af+ 0x03c4 normal_boot_spare_error_ack
af+ 0x0424 normal_boot_color_test_done
af+ 0x04a4 normal_boot_playfield_test_done
af+ 0x0512 normal_boot_alpha_test_done
af+ 0x0582 normal_boot_mob_test_done
af+ 0x0652 selftest_spare_test_done
af+ 0x0660 selftest_spare_error_ack
af+ 0x067c selftest_color_test_done
af+ 0x06a6 selftest_playfield_test_done
af+ 0x06d0 selftest_alpha_test_done
af+ 0x06fc selftest_mob_test_done
af+ 0x08ec boot_postcheck_dispatch
af+ 0x0a42 mem_test_short_walk_ones
af+ 0x0a52 mem_test_short_walk_zeroes
af+ 0x0a62 mem_test_short_done
af+ 0x0a7a mem_test_full_walk_ones_highbit
af+ 0x0a84 mem_test_full_walk_zeroes_highbit
af+ 0x0a8e mem_test_full_walk_ones_lowbit
af+ 0x0a98 mem_test_full_walk_zeroes_lowbit
af+ 0x0aa2 mem_test_full_restore_ones_highbit
af+ 0x0aac mem_test_full_restore_ones_lowbit
af+ 0x0ab6 mem_test_full_fill_ones
af+ 0x0ac2 mem_test_full_restore_zeroes_highbit
af+ 0x0acc mem_test_full_restore_zeroes_lowbit
af+ 0x0ad6 mem_test_full_toggle_words
af+ 0x0ae0 mem_test_full_done
af+ 0x0d26 game_descriptor_ram_test
af+ 0x0d3a game_descriptor_ram_test_done
af+ 0x0d7a game_rom_checksum_error
af+ 0x0eee selftest_watchdog_reset_trap
af+ 0x0f04 playfield_add_word_test_range
af+ 0x0f7e copy_test_tile_rows_to_alpha
af+ 0x113e read_debounced_input
af+ 0x11fc color_test_palette_init
af+ 0x1228 selftest_load_control_labels
af+ 0x169c load_color_test_palettes
af+ 0x16f6 copy_cstring
af+ 0x1704 reset_sound_test_interface
af+ 0x1732 fill_incrementing_words
af+ 0x1758 display_standard_large_glyph_range
af+ 0x179e display_rotated_large_glyph_range
af+ 0x1a34 run_switch_test
af+ 0x2190 wait_os_vblank
af+ 0x226a display_next_test_prompt
af+ 0x229c run_sound_test
af+ 0x27ac send_sound_test_command_wait
af+ 0x27f4 wait_sound_test_delay_or_abort
af+ 0x2828 display_ram_error_detail
af+ 0x28ca display_two_byte_hex_pair
af+ 0x2d14 rotate_text_line_forward
af+ 0x2d18 rotate_text_line_forward_register
af+ 0x2d74 rotate_text_line_reverse
af+ 0x2d78 rotate_text_line_reverse_register
af+ 0x2dde scroll_alpha_surface_one_step
af+ 0x2e3e display_text_register
af+ 0x2f3c draw_string_register
af+ 0x2fb2 draw_text_effect_next_char_stack_veneer
af+ 0x2fbe draw_text_effect_next_char
af+ 0x3018 clear_text_effect_next_char_stack_veneer
af+ 0x3020 clear_text_effect_next_char
af+ 0x304e write_alpha_char_register
af+ 0x3088 clear_text_descriptor_chain_stack_veneer
af+ 0x308c clear_text_descriptor_chain
af+ 0x3166 unused_text_effect_noop
af+ 0x3172 allocate_text_effect
af+ 0x324e render_large_glyph_register
af+ 0x355c reset_text_effects
af+ 0x3d18 write_game_config
af+ 0x4198 send_sound_command_register
af+ 0x4674 eeprom_decode_block
af+ 0x467c eeprom_decode_block_to
af+ 0x4770 eeprom_clear_statistics
af+ 0x4784 eeprom_clear_configuration
af+ 0x47ac eeprom_request_write_register
af+ 0x47b8 eeprom_clear_difficulty_rows
af+ 0x4896 wait_vblank_counter_ticks
af+ 0x48b8 display_text_set_cursor
af+ 0x4912 display_text_at_cursor
af+ 0x493c display_decimal_at_cursor
af+ 0x4966 display_decimal_set_cursor
af+ 0x49c8 option_record_present
af+ 0x49e8 find_option_record
af+ 0x4a44 render_option_record
af+ 0x4b66 render_option_record_page
af+ 0x4be6 display_next_screen_prompt
af+ 0x4c38 init_operator_mob_display
af+ 0x4c66 run_statistics_histograms
af+ 0x4fa0 display_statistics_play_time
af+ 0x5098 run_statistics_summary
af+ 0x522a run_game_settings_bit_editor
af+ 0x5392 draw_game_settings_bits
af+ 0x5476 run_option_descriptor_editor
af+ 0x593c run_coin_options
af+ 0x8000 legacy_monster_object_update
af+ 0x8702 legacy_monster_choose_direction
af+ 0x89aa legacy_four_cell_occupied_test
af+ 0x89e6 legacy_position_in_active_bounds
af+ 0x8a12 legacy_set_direction_from_delta
af+ 0x8ae8 legacy_moblist_insert
af+ 0x8c36 legacy_move_mob_slot
af+ 0x8c70 legacy_moblist_remove_and_clear
af+ 0x8d00 legacy_moblist_unlink
af+ 0x8f38 legacy_probe_up
af+ 0x9006 legacy_probe_down
af+ 0x90d2 legacy_probe_left
af+ 0x9192 legacy_probe_right
af+ 0x9284 legacy_recursive_path_move
af+ 0x9864 legacy_test_actor_contact_a
af+ 0x9880 legacy_test_actor_contact_b
af+ 0x989c legacy_probe_vertical_triplet_up
af+ 0x98d8 legacy_probe_vertical_triplet_down
af+ 0x9914 legacy_test_cell_proximity
af+ 0x99a0 legacy_probe_horizontal_triplet_left
af+ 0x99d8 legacy_probe_horizontal_triplet_right
af+ 0x40000 game_start_veneer
af+ 0x40006 game_vblank_veneer
af+ 0x4000c game_irq1_watchdog_trap
af+ 0x40012 game_irq3_watchdog_trap
af+ 0x40018 game_irq2_watchdog_trap
af+ 0x4001e game_irq6_sound_veneer
af+ 0x40024 game_exception_veneer
af+ 0x40030 game_playfield_init_veneer
af+ 0x40048 game_options_veneer
af+ 0x40054 game_rom_verify_veneer
af+ 0x400de scroll_to_slot_veneer
af+ 0x400e4 init_display_veneer
af+ 0x400ea maze_setup_veneer
af+ 0x400f0 pf_replace_veneer
af+ 0x400f6 mob_clear_veneer
af+ 0x40140 game_exception_abort
af+ 0x4014c game_start
af+ 0x4017e game_vblank
af+ 0x404a0 palette_power_warrior
af+ 0x404ae palette_hurt_warrior
af+ 0x404bc palette_power_valkyrie
af+ 0x404d0 palette_hurt_valkyrie
af+ 0x404e4 palette_power_wizard
af+ 0x404f8 palette_hurt_wizard
af+ 0x4050c palette_power_elf
af+ 0x4051a palette_hurt_elf
af+ 0x40528 main_cycle_tport_and_ffield
af+ 0x40628 calc_score_per_coin
af+ 0x40644 input_debounce
af+ 0x406b6 mob_probe_up
af+ 0x40732 mob_probe_down
af+ 0x407a6 mob_probe_candidate
af+ 0x4083a mob_probe_left
af+ 0x408a0 mob_probe_right
af+ 0x40906 shot_mob_collision
af+ 0x40a78 shot_collision_candidate_core
af+ 0x40c78 find_maze
af+ 0x40cc4 maze_select_alt_bank
af+ 0x40cf2 maze_init
af+ 0x40d24 load_level_tileset
af+ 0x40d4e maze_select_bank_special
af+ 0x40e6a monsters_everything
af+ 0x40fae monster_loop_core
af+ 0x4119a monster_special_handler
af+ 0x414a4 monster_update_anim_tile
af+ 0x41750 monster_find_and_shoot
af+ 0x41b16 find_unused_shot
af+ 0x41b52 monster_shooter_in_view
af+ 0x41b7e apply_direction_from_delta
af+ 0x41bf0 player_try_move
af+ 0x41c30 player_try_move_core
af+ 0x42598 mob_collision_test_preserve_d1_a
af+ 0x425b4 mob_collision_test_preserve_d1_b
af+ 0x425d0 probe_up
af+ 0x4260c probe_down
af+ 0x42648 tile_lookup_core
af+ 0x426d4 probe_left
af+ 0x4270c probe_right
af+ 0x42744 squeeze_through_check
af+ 0x427b4 failed_door_post
af+ 0x4280e door_traverse_right
af+ 0x428a4 door_traverse_left
af+ 0x4293a door_traverse_up
af+ 0x429d0 door_traverse_down
af+ 0x42a66 g2mainloop
af+ 0x42b6a coincheck
af+ 0x42d0a sound_response
af+ 0x42dc8 sound_system_reset
af+ 0x42df4 character_select_input_update
af+ 0x42e9a maze_randomplace
af+ 0x42f86 eeprom_load_config
af+ 0x43192 eeprom_write
af+ 0x431ee eeprom_periodic_write
af+ 0x4327a one_time_init
af+ 0x43360 player_resetcounters
af+ 0x4341e player_resetall
af+ 0x43486 init_display
af+ 0x436cc get_random_maze_flags
af+ 0x436fe maze_load_pickup_config
af+ 0x43826 slapstic_cmd_bitwise
af+ 0x438ae maze_new_level_setup
af+ 0x43d8c maze_scan_objects
af+ 0x43f68 maze_addrandompickups
af+ 0x44204 start_attract_to_game
af+ 0x4438e load_attract_display_tilemap
af+ 0x44414 start_attract_screen
af+ 0x44562 main_attract
af+ 0x449cc attract_noop_hook
af+ 0x449d4 attract_demo_init
af+ 0x44a82 game_playfield_init
af+ 0x44ac2 maze_setupnew
af+ 0x44c7e show_continue_prompt
af+ 0x44db4 show_level_start_screen
af+ 0x4526a maze_show
af+ 0x4529a maze_hide
af+ 0x452d0 setup_infopanel
af+ 0x457c0 main_score_display
af+ 0x45866 player_it_label_set
af+ 0x4590e player_it_label_clear
af+ 0x45940 draw_player_score
af+ 0x459a2 draw_player_health
af+ 0x45aca player_inv_update
af+ 0x45be8 string_length
af+ 0x45c00 main_open_doors
af+ 0x45e40 maze_place_object
af+ 0x462ae dragon_reserve_footprint_cell
af+ 0x4631c maze_tile_write_at
af+ 0x4664c main_handle_death
af+ 0x466f6 main_health_countdown
af+ 0x46c5e scroll_to_slot
af+ 0x46caa main_scroll_playfield
af+ 0x46f56 set_scroll_pos
af+ 0x46fea main_handle_potions
af+ 0x4715e main_score_update
af+ 0x474f6 main_handle_shots
af+ 0x47c0e tport_cycle_start
af+ 0x47cfe handle_tport
af+ 0x47dae shot_impact_spawn
af+ 0x47fac open_timed_doors
af+ 0x4800c main_start_game
af+ 0x486fe secret_check
af+ 0x48754 speech_welcome
af+ 0x487ca player_lowhealth
af+ 0x488ca player_coindrop
af+ 0x489b8 remove_dying_player_sprites
af+ 0x48a36 player_join_finalize
af+ 0x48b58 update_monster_bonus_from_score_per_coin
af+ 0x48bb6 player_join
af+ 0x48bec player_start_inner
af+ 0x48f12 tile_occupancy_test
af+ 0x49034 main_move_monsters
af+ 0x490dc monster_create_shot
af+ 0x492c0 handle_generate
af+ 0x49446 death_potion_score
af+ 0x49498 playfield_showscore
af+ 0x495a6 monster_playerhit
af+ 0x49a3c death_damage_accumulate
af+ 0x49a98 player_hurt_speech_timer
af+ 0x49b44 ascii_to_alpha_glyph
af+ 0x49bd0 highscore_table_init
af+ 0x49d0e highscore_check
af+ 0x49de6 player_death_sequence
af+ 0x4a124 attract_highscores
af+ 0x4a2ca draw_player_initials_entry
af+ 0x4a44a name_entry_draw_large_char
af+ 0x4a53a main_move_players
af+ 0x4ad4e sound_speech_play
af+ 0x4ad76 sound_play
af+ 0x4adae sound_queue_reset
af+ 0x4add6 enqueue_sound
af+ 0x4ae20 main_update_sound
af+ 0x4aea0 shot_onscreen_check
af+ 0x4af50 resolve_shot_hit
af+ 0x4be24 level_splash
af+ 0x4c1bc maze_decode
af+ 0x4c440 dialog_first_encounter
af+ 0x4c70a dialog_clear_message
af+ 0x4c72a player_give_item_with_message
af+ 0x4c9a2 demo_speech_cmd
af+ 0x4cb50 dialog_position_box
af+ 0x4ccbc main_msgbox_countdown
af+ 0x4cd1c load_legend_page
af+ 0x4cdb8 draw_legend_monsters_page
af+ 0x4cfae draw_legend_overview_page
af+ 0x4cfda draw_legend_rules_page
af+ 0x4d12e alpha_clear_rect
af+ 0x4d1a4 secret_bonus_earned
af+ 0x4d29e main_treasure_timer
af+ 0x4d476 show_level_end_bonus_screen
af+ 0x4d900 player_activecount
af+ 0x4d956 scroll_apply
af+ 0x4da3e title_logo_init
af+ 0x4dcba main_logo_updcolors
af+ 0x4de76 score_screen_color_cycle
af+ 0x4deb8 main_start_thief
af+ 0x4dff6 thief_target_calc
af+ 0x4e122 thief_exit
af+ 0x4e172 thief_end_dodge
af+ 0x4e1b8 thief_begin_dodge
af+ 0x4e1fe thief_steal_from_player
af+ 0x4e432 thief_setup
af+ 0x4e4d8 thief_timer_set
af+ 0x4e630 thief_track_victim_move
af+ 0x4e684 tport_route_connect
af+ 0x4e73a tport_route_connect_if_empty
af+ 0x4e7c0 tport_find_id
af+ 0x4e7fc thief_test_move_tile
af+ 0x4e8dc main_thief_anim
af+ 0x4ee0a thief_probe_axis
af+ 0x4ee7a thief_move_engine
af+ 0x4f5c8 thief_remove_and_drop_loot
af+ 0x4f742 thief_handle_tile_collision
af+ 0x4f912 thief_compute_path
af+ 0x4fad4 thief_enter_tport
af+ 0x4fbfc thief_start_tport_anim
af+ 0x4fcf0 thief_find_aligned_shooter
af+ 0x4feb2 corner_squeeze_geometry
af+ 0x50224 player_tport
af+ 0x50616 tport_player_flash
af+ 0x50662 tport_player_move
af+ 0x50ade tport_check_dest
af+ 0x50b88 tport_restore_player_picture
af+ 0x50bb8 scan_move_path_interactions
af+ 0x50c7a resolve_move_tile_interaction
af+ 0x50d14 nearby_mob_clearance_test
af+ 0x50e34 player_damage_sample_update
af+ 0x50fd2 path_grid_set_low_direction
af+ 0x51000 path_grid_set_high_direction_if_empty
af+ 0x5103e path_grid_get_direction
af+ 0x5107a tport_route_write_pair
af+ 0x510bc tport_route_read_pair
af+ 0x510fc calc_direction
af+ 0x511ac player_tile_interact
af+ 0x51e80 door_record_endpoints
af+ 0x51fae door_scan_vertical_endpoints
af+ 0x5207c door_scan_horizontal_endpoints
af+ 0x5214c player_add_score_with_mult
af+ 0x52192 mob_collision_test
af+ 0x5287c main_exit_move
af+ 0x52b06 exit_get_id
af+ 0x52b40 player_exit_sequence
af+ 0x52eca maze_checknum
af+ 0x52f26 maze_forcefield_setup
af+ 0x52fbe consume_forcefield_code
af+ 0x5303a wall_crumble
af+ 0x5317c game_options_display
af+ 0x53346 check_forcefield_collision
af+ 0x53398 forcefield_segments_setup
af+ 0x53666 player_create_shot
af+ 0x53818 shot_reflect_calc
af+ 0x53d10 dragon_update_segments
af+ 0x53e4a dragon_choose_move_direction
af+ 0x540e8 dragon_find_free_shot_slot
af+ 0x54112 dragon_shot_hit
af+ 0x54454 main_handle_dragon
af+ 0x54748 dragon_fire_setup
af+ 0x5496e dragon_setup_segments
af+ 0x549ea dragon_player_proximity
af+ 0x54af8 dragon_any_segment_near_screen
af+ 0x54b68 dragon_shot_hitbox_adjust
af+ 0x54be0 secret_code_build
af+ 0x54ec6 secret_getname
af+ 0x54fe8 secret_name_entry_update
af+ 0x55440 name_entry_step_char
af+ 0x554b6 name_entry_draw_char
af+ 0x5554e name_entry_step_char_copy
af+ 0x555c4 name_entry_draw_char_copy
af+ 0x56e58 slapstic_cmd_bank0
af+ 0x56e6e slapstic_cmd_bank3
af+ 0x56e84 slapstic_cmd_bankX
af+ 0x56e90 slapstic_cmd_maze_init
af+ 0x56e98 slapstic_cmd_bankX_special
af+ 0x56eaa slapstic_verify
af+ 0x5dc58 mob_create
af+ 0x5dcbc moblist_insert
af+ 0x5dd72 moblist_replace
af+ 0x5dda8 moblist_remove
af+ 0x5ddda moblist_remove_and_clear
af+ 0x5de0a move_mob_slot
af+ 0x5de44 moblist_remove_and_clear_regs
af+ 0x5ded4 moblist_unlink_regs
af+ 0x5df5a mob_place_tport_anim
af+ 0x5df68 mob_place_shot
af+ 0x5df72 mob_place_anim
af+ 0x5df80 exit_create_player_anim
af+ 0x5df8e tport_create_splodey
af+ 0x5df9c mob_place_explosion
af+ 0x5dfa6 insert_mob_depth_sorted
af+ 0x5e064 mob_depth_remove
af+ 0x5e10c ray_march_down
af+ 0x5e1d8 ray_march_up
af+ 0x5e2a2 ray_march_left
af+ 0x5e35e ray_march_right
af+ 0x5e41a main_walls_random_move
af+ 0x5e536 pf_stamp_update
af+ 0x5e542 pf_stamp_update_regs
af+ 0x5e57e tile_on_screen_d4
af+ 0x5e584 tile_on_screen_test
af+ 0x5e5d2 tile_near_screen_d4
af+ 0x5e5d8 tile_near_screen_test
af+ 0x5e62a main_walls_cyclic_move
af+ 0x5e7a6 maze_place_object_types
af+ 0x5e80c maze_convert_walls_to_exits
af+ 0x5e868 maze_special_floor
af+ 0x5e888 pf_floor_draw_xy
af+ 0x5e892 pf_floor_update
af+ 0x5ea00 maze_floor_decor
af+ 0x5ea26 pf_isblankfloor_stack
af+ 0x5ea2e pf_isblankfloor
af+ 0x5ea66 pf_is_connectable_floor_xy
af+ 0x5eab8 pf_wall_draw
af+ 0x5eac2 pf_wall_draw_stack
af+ 0x5f024 wall_place_playfield_update
af+ 0x5f2c0 maze_init_walls
af+ 0x5f310 mob_place_tile
af+ 0x5f31e pf_replace
af+ 0x5f598 refresh_tile_visual_stack
af+ 0x5f5a0 refresh_tile_visual
af+ 0x5f644 refresh_tile_visual_legacy
af+ 0x5f772 pf_isdoor_stack
af+ 0x5f77a pf_isdoor
af+ 0x5f7c0 maze_doors_setup
af+ 0x5f7f0 pf_door_update_surrounding_xy
af+ 0x5f7fa pf_door_update_surrounding
af+ 0x5f876 pf_door_draw_xy
af+ 0x5f880 pf_door_draw
af+ 0x5fc22 random_seeded
af+ 0x5fc26 random_bound_stack_core
af+ 0x5fc2c random_core
af+ 0x5fc46 random_word
af+ 0x5fc4e getrandom
af+ 0x5fc56 pf_isff_d0
af+ 0x5fc5e pf_isff
af+ 0x5fcce pf_palette_clear
af+ 0x5fd14 display_state_clear
af+ 0x5fd58 memclear
af+ 0x5fd64 memclear_core
af+ 0x5fd6a copy_longwords
af+ 0x5fd80 palette_fade_copy
af+ 0x5fdb8 supersorc_place_helper
af+ 0x5fde0 supersorc_place
f exception_handler 1 0x00000300
f irq1_handler 1 0x00000314
f irq2_handler 1 0x00000326
f irq3_handler 1 0x00000338
f irq4_vblank_handler 1 0x0000034a
f irq6_handler 1 0x0000036c
f normal_boot 1 0x000003a0
f reset_entry 1 0x000005e2
f selftest_boot 1 0x0000061e
f main_init_cont 1 0x0000070c
f mem_test_short 1 0x00000a2c
f mem_test_full 1 0x00000a6a
f display_working_ram_error 1 0x00000c52
f error_display_ram 1 0x00000c98
f rom_checksum_display 1 0x00000cc0
f os_vblank_mode_entry 1 0x00000e14
f os_vblank_handler 1 0x00000e5e
f run_color_test 1 0x00000fca
f os_selftest_loop 1 0x0000129a
f display_init_clear 1 0x00001632
f run_alpha_test 1 0x000017d4
f run_motion_object_test 1 0x00001b20
f validate_game_rom 1 0x000021a0
f format_number 1 0x00002918
f format_hex 1 0x00002a5e
f format_decimal 1 0x00002abe
f process_text_effects 1 0x00002b3c
f calc_alpha_address 1 0x00002ce4
f display_text 1 0x00002e36
f display_decimal_value 1 0x00002eb4
f display_hex_value 1 0x00002eea
f draw_string 1 0x00002f04
f write_alpha_char 1 0x00003044
f stop_text_effect 1 0x000030f4
f start_text_line_rotation 1 0x00003122
f init_fullscreen_text_scroll 1 0x00003130
f start_progressive_text_clear 1 0x00003156
f start_blink_text 1 0x00003162
f start_timed_text 1 0x00003168
f start_progressive_text 1 0x0000316c
f display_large_text 1 0x000031d2
f display_large_char_raw 1 0x000032a0
f display_large_char_at 1 0x000032bc
f display_large_decimal_value 1 0x000032da
f display_large_hex_value 1 0x00003310
f display_large_text_at 1 0x0000332a
f clear_large_text 1 0x00003346
f init_alpha_display 1 0x00003522
f write_alpha_word 1 0x00003586
f wait_vblanks 1 0x0000359a
f set_text_position 1 0x000035b2
f process_coins 1 0x000035c4
f get_coin_multiplier 1 0x00003706
f calc_health_per_coin 1 0x00003740
f check_and_deduct_coin 1 0x000037c2
f check_and_deduct_credits 1 0x00003804
f read_eeprom_setting 1 0x00003860
f read_game_config 1 0x000038c0
f read_high_score_entry 1 0x000039b0
f write_high_score_entry 1 0x00003a7e
f update_active_player_time_stats 1 0x00003be8
f write_eeprom_setting 1 0x00003cf6
f rank_high_score 1 0x00003f68
f activate_player_time_tracking 1 0x0000401a
f record_player_session_histogram 1 0x00004038
f send_sound_command 1 0x00004184
f send_sound_command_wait 1 0x000041c8
f try_send_sound_command 1 0x000041cc
f process_sound 1 0x000041fa
f sound_receive_irq_body 1 0x0000427a
f read_sound_data 1 0x000042c8
f reset_sound_cpu 1 0x000042f8
f eeprom_process 1 0x0000432e
f eeprom_init 1 0x000044e8
f eeprom_request_write 1 0x000047a8
f eeprom_check_busy 1 0x00004802
f eeprom_read_block 1 0x00004822
f run_statistics_screens 1 0x00005454
f run_game_options 1 0x000058c6
f game_start_veneer 6 0x00040000
f game_vblank_veneer 6 0x00040006
f game_irq1_watchdog_trap 6 0x0004000c
f game_irq3_watchdog_trap 6 0x00040012
f game_irq2_watchdog_trap 6 0x00040018
f game_irq6_sound_veneer 6 0x0004001e
f game_exception_veneer 6 0x00040024
f game.startup_hook2_slot 6 0x0004002a
f game_playfield_init_veneer 6 0x00040030
f game.startup_hook1_slot 6 0x00040036
f game.startup_hook3_slot 6 0x0004003c
f game.vblank_hook_slot 6 0x00040042
f game_options_veneer 6 0x00040048
f game.post_attract_hook_slot 6 0x0004004e
f game_rom_verify_veneer 6 0x00040054
f game.header_ff_pad_4005a 6 0x0004005a
f game.mob_fill_value 2 0x00040060
f game.pf_fill_value 2 0x00040062
f game.reserved_header_40064 9 0x00040064
f game.eeprom_start 1 0x0004006d
f game.reserved_header_4006e 1 0x0004006e
f game.difficulty_byte 1 0x0004006f
f game.default_settings 2 0x00040070
f game.rom_type_flag 1 0x00040072
f game.reserved_header_40073 1 0x00040073
f game.button0_label_ptr 4 0x00040074
f game.button1_label_ptr 4 0x00040078
f game.joystick_label_ptr 4 0x0004007c
f game.checksum_table 24 0x00040080
f game.header_zero_pad_40098 4 0x00040098
f game.copyright_morse_signature 9 0x0004009c
f game.header_ff_pad 57 0x000400a5
f scroll_to_slot_veneer 6 0x000400de
f init_display_veneer 6 0x000400e4
f maze_setup_veneer 6 0x000400ea
f pf_replace_veneer 6 0x000400f0
f mob_clear_veneer 6 0x000400f6
f game.unreferenced_ram_value_pair 6 0x000400fc
f game.joystick_label 17 0x00040102
f game.fire_label 22 0x00040113
f game.magic_label 23 0x00040129
f game_exception_abort 12 0x00040140
f game_start 1 0x0004014c
f game_vblank 1 0x0004017e
f palette_power_warrior 14 0x000404a0
f palette_hurt_warrior 14 0x000404ae
f palette_power_valkyrie 20 0x000404bc
f palette_hurt_valkyrie 20 0x000404d0
f palette_power_wizard 20 0x000404e4
f palette_hurt_wizard 20 0x000404f8
f palette_power_elf 14 0x0004050c
f palette_hurt_elf 14 0x0004051a
f main_cycle_tport_and_ffield 1 0x00040528
f forcefield_color_steps 8 0x000405c0
f palette_offset_by_walltype 16 0x000405c8
f palette_offset2_by_walltype 16 0x000405d8
f vscroll_alpha_gradient 64 0x000405e8
f calc_score_per_coin 1 0x00040628
f input_debounce 1 0x00040644
f mob_probe_up 1 0x000406b6
f mob_probe_down 1 0x00040732
f mob_probe_candidate 1 0x000407a6
f mob_probe_left 1 0x0004083a
f mob_probe_right 1 0x000408a0
f shot_mob_collision 1 0x00040906
f shot_collision_candidate_core 1 0x00040a78
f mob_collision_type_filter 64 0x00040b58
f shot_collision_width 24 0x00040b98
f shot_collision_height 24 0x00040bb0
f dragon_shot_collision_width 8 0x00040bc8
f dragon_shot_collision_height 8 0x00040bd0
f shot_collision_probe_offsets 160 0x00040bd8
f find_maze 1 0x00040c78
f maze_select_alt_bank 1 0x00040cc4
f maze_init 1 0x00040cf2
f load_level_tileset 1 0x00040d24
f maze_select_bank_special 1 0x00040d4e
f monster_kill_score_by_multiplier 18 0x00040d78
f monster_shoot_axis_thresholds 40 0x00040d8a
f monster_anim_idle_ptrs 40 0x00040db2
f monster_anim_moving_ptrs 40 0x00040dda
f monster_level_flag_overrides 28 0x00040e02
f monster_oddangle_table 40 0x00040e1e
f monster_count_table 32 0x00040e46
f dead_monster_count_tail_words 4 0x00040e66
f monsters_everything 1 0x00040e6a
f monster_loop_core 1 0x00040fae
f monster_special_handler 1 0x0004119a
f monster_update_anim_tile 1 0x000414a4
f monster_find_and_shoot 1 0x00041750
f find_unused_shot 1 0x00041b16
f monster_shooter_in_view 1 0x00041b52
f apply_direction_from_delta 1 0x00041b7e
f player_character_collision_block_matrix 32 0x00041bd0
f player_try_move 1 0x00041bf0
f player_try_move_core 1 0x00041c30
f mob_collision_test_preserve_d1_a 1 0x00042598
f mob_collision_test_preserve_d1_b 1 0x000425b4
f probe_up 1 0x000425d0
f probe_down 1 0x0004260c
f tile_lookup_core 1 0x00042648
f probe_left 1 0x000426d4
f probe_right 1 0x0004270c
f squeeze_through_check 1 0x00042744
f failed_door_post 1 0x000427b4
f door_traverse_right 1 0x0004280e
f door_traverse_left 1 0x000428a4
f door_traverse_up 1 0x0004293a
f door_traverse_down 1 0x000429d0
f g2mainloop 1 0x00042a66
f coincheck 1 0x00042b6a
f sound_response 1 0x00042d0a
f sound_system_reset 1 0x00042dc8
f character_select_input_update 1 0x00042df4
f maze_randomplace 1 0x00042e9a
f eeprom_load_config 1 0x00042f86
f eeprom_write 1 0x00043192
f eeprom_periodic_write 1 0x000431ee
f one_time_init 1 0x0004327a
f player_resetcounters 1 0x00043360
f player_resetall 1 0x0004341e
f init_display 1 0x00043486
f get_random_maze_flags 1 0x000436cc
f maze_load_pickup_config 1 0x000436fe
f slapstic_cmd_bitwise 1 0x00043826
f maze_new_level_setup 1 0x000438ae
f maze_scan_objects 1 0x00043d8c
f maze_addrandompickups 1 0x00043f68
f start_attract_to_game 1 0x00044204
f load_attract_display_tilemap 1 0x0004438e
f start_attract_screen 1 0x00044414
f main_attract 1 0x00044562
f attract_noop_hook 1 0x000449cc
f attract_demo_init 1 0x000449d4
f game_playfield_init 1 0x00044a82
f maze_setupnew 1 0x00044ac2
f show_continue_prompt 1 0x00044c7e
f show_level_start_screen 1 0x00044db4
f maze_show 1 0x0004526a
f maze_hide 1 0x0004529a
f setup_infopanel 1 0x000452d0
f main_score_display 1 0x000457c0
f player_it_label_set 1 0x00045866
f player_it_label_clear 1 0x0004590e
f draw_player_score 1 0x00045940
f draw_player_health 1 0x000459a2
f player_inv_update 1 0x00045aca
f string_length 1 0x00045be8
f door_open_direction_jumptbl 8 0x00045c46
f main_open_doors 1 0x00045c00
f maze_place_object 1 0x00045e40
f dragon_reserve_footprint_cell 1 0x000462ae
f maze_tile_write_at 1 0x0004631c
f main_handle_death 1 0x0004664c
f main_health_countdown 1 0x000466f6
f scroll_to_slot 1 0x00046c5e
f main_scroll_playfield 1 0x00046caa
f set_scroll_pos 1 0x00046f56
f main_handle_potions 1 0x00046fea
f main_score_update 1 0x0004715e
f main_handle_shots 1 0x000474f6
f tport_cycle_start 1 0x00047c0e
f handle_tport 1 0x00047cfe
f shot_impact_spawn 1 0x00047dae
f open_timed_doors 1 0x00047fac
f main_start_game 1 0x0004800c
f secret_check 1 0x000486fe
f speech_welcome 1 0x00048754
f player_lowhealth 1 0x000487ca
f player_coindrop 1 0x000488ca
f remove_dying_player_sprites 1 0x000489b8
f player_join_finalize 1 0x00048a36
f update_monster_bonus_from_score_per_coin 1 0x00048b58
f player_join 1 0x00048bb6
f player_start_inner 1 0x00048bec
f tile_occupancy_test 1 0x00048f12
f main_move_monsters 1 0x00049034
f monster_create_shot 1 0x000490dc
f handle_generate 1 0x000492c0
f death_potion_score 1 0x00049446
f playfield_showscore 1 0x00049498
f monster_playerhit 1 0x000495a6
f monster_playerhit_jumptbl 20 0x00049620
f death_damage_accumulate 1 0x00049a3c
f player_hurt_speech_timer 1 0x00049a98
f ascii_to_alpha_glyph 1 0x00049b44
f highscore_table_init 1 0x00049bd0
f highscore_check 1 0x00049d0e
f player_death_sequence 1 0x00049de6
f attract_highscores 1 0x0004a124
f draw_player_initials_entry 1 0x0004a2ca
f name_entry_draw_large_char 1 0x0004a44a
f stun_direction_remap 64 0x0004a4fa
f main_move_players 1 0x0004a53a
f sound_speech_play 1 0x0004ad4e
f sound_play 1 0x0004ad76
f sound_queue_reset 1 0x0004adae
f enqueue_sound 1 0x0004add6
f main_update_sound 1 0x0004ae20
f shot_onscreen_check 1 0x0004aea0
f resolve_shot_hit 1 0x0004af50
f resolve_shot_hit_jumptbl 124 0x0004b338
f level_splash 1 0x0004be24
f maze_decode 1 0x0004c1bc
f dialog_first_encounter 1 0x0004c440
f dialog_clear_message 1 0x0004c70a
f player_give_item_with_message 1 0x0004c72a
f demo_speech_cmd 1 0x0004c9a2
f dialog_position_box 1 0x0004cb50
f main_msgbox_countdown 1 0x0004ccbc
f load_legend_page 1 0x0004cd1c
f draw_legend_monsters_page 1 0x0004cdb8
f draw_legend_overview_page 1 0x0004cfae
f draw_legend_rules_page 1 0x0004cfda
f alpha_clear_rect 1 0x0004d12e
f secret_bonus_earned 1 0x0004d1a4
f main_treasure_timer 1 0x0004d29e
f show_level_end_bonus_screen 1 0x0004d476
f player_activecount 1 0x0004d900
f scroll_apply 1 0x0004d956
f title_logo_init 1 0x0004da3e
f main_logo_updcolors 1 0x0004dcba
f score_screen_color_cycle 1 0x0004de76
f main_start_thief 1 0x0004deb8
f thief_target_calc 1 0x0004dff6
f thief_exit 1 0x0004e122
f thief_end_dodge 1 0x0004e172
f thief_begin_dodge 1 0x0004e1b8
f thief_steal_from_player 1 0x0004e1fe
f thief_setup 1 0x0004e432
f thief_timer_set 1 0x0004e4d8
f thief_track_victim_move 1 0x0004e630
f tport_route_connect 1 0x0004e684
f tport_route_connect_if_empty 1 0x0004e73a
f tport_find_id 1 0x0004e7c0
f thief_test_move_tile 1 0x0004e7fc
f main_thief_anim 1 0x0004e8dc
f thief_probe_axis 1 0x0004ee0a
f thief_move_engine 1 0x0004ee7a
f thief_remove_and_drop_loot 1 0x0004f5c8
f thief_handle_tile_collision 1 0x0004f742
f thief_compute_path 1 0x0004f912
f thief_enter_tport 1 0x0004fad4
f thief_start_tport_anim 1 0x0004fbfc
f thief_find_aligned_shooter 1 0x0004fcf0
f richest_player_tie_jumptbl 16 0x0004fe08
f corner_squeeze_geometry 1 0x0004feb2
f player_tport 1 0x00050224
f tport_player_flash 1 0x00050616
f tport_player_move 1 0x00050662
f tport_check_dest 1 0x00050ade
f tport_restore_player_picture 1 0x00050b88
f scan_move_path_interactions 1 0x00050bb8
f resolve_move_tile_interaction 1 0x00050c7a
f nearby_mob_clearance_test 1 0x00050d14
f player_damage_sample_update 1 0x00050e34
f path_grid_set_low_direction 1 0x00050fd2
f path_grid_set_high_direction_if_empty 1 0x00051000
f path_grid_get_direction 1 0x0005103e
f tport_route_write_pair 1 0x0005107a
f tport_route_read_pair 1 0x000510bc
f calc_direction 1 0x000510fc
f player_tile_lowtype_jumptbl 16 0x00051200
f player_tile_object_jumptbl 34 0x0005122a
f player_tile_interact 1 0x000511ac
f door_record_endpoints 1 0x00051e80
f door_scan_vertical_endpoints 1 0x00051fae
f door_scan_horizontal_endpoints 1 0x0005207c
f player_add_score_with_mult 1 0x0005214c
f mob_collision_test 1 0x00052192
f mob_collision_object_jumptbl 94 0x00052210
f dead_mob_collision_jump_tail 12 0x0005226e
f main_exit_move 1 0x0005287c
f exit_get_id 1 0x00052b06
f player_exit_sequence 1 0x00052b40
f maze_checknum 1 0x00052eca
f maze_forcefield_setup 1 0x00052f26
f consume_forcefield_code 1 0x00052fbe
f wall_crumble 1 0x0005303a
f game_options_display 1 0x0005317c
f game_options_descriptor_stream 442 0x0005318c
f check_forcefield_collision 1 0x00053346
f forcefield_segments_setup 1 0x00053398
f player_create_shot 1 0x00053666
f shot_reflect_calc 1 0x00053818
f shot_reflect_center_jumptbl 10 0x000538fe
f shot_reflect_neg42_jumptbl 10 0x00053924
f shot_reflect_neg22_jumptbl 10 0x00053948
f shot_reflect_pos1e_jumptbl 10 0x0005396a
f shot_reflect_pos3e_jumptbl 10 0x00053992
f dragon_update_segments 1 0x00053d10
f dragon_choose_move_direction 1 0x00053e4a
f dragon_find_free_shot_slot 1 0x000540e8
f dragon_shot_hit 1 0x00054112
f main_handle_dragon 1 0x00054454
f dragon_fire_setup 1 0x00054748
f dragon_setup_segments 1 0x0005496e
f dragon_player_proximity 1 0x000549ea
f dragon_any_segment_near_screen 1 0x00054af8
f dragon_shot_hitbox_adjust 1 0x00054b68
f dragon_head_hitbox_offsets 10 0x00054bd6
f secret_code_build 1 0x00054be0
f secret_code_alphabet 32 0x00054ca6
f secret_code_crc16_table 512 0x00054cc6
f secret_getname 1 0x00054ec6
f secret_name_entry_update 1 0x00054fe8
f name_entry_step_char 1 0x00055440
f name_entry_draw_char 1 0x000554b6
f dead_name_entry_epilogue_fragments 60 0x00055512
f name_entry_step_char_copy 1 0x0005554e
f name_entry_draw_char_copy 1 0x000555c4
f slapstic_cmd_bank0 1 0x00056e58
f slapstic_cmd_bank3 1 0x00056e6e
f slapstic_cmd_bankX 1 0x00056e84
f slapstic_cmd_maze_init 1 0x00056e90
f slapstic_cmd_bankX_special 1 0x00056e98
f slapstic_verify 1 0x00056eaa
f dead_slapstic_verify_suffix 76 0x00056f5c
f pad_56fa8 90 0x00056fa8
f character_announcement_speech_ptrs 16 0x00057002
f random_maze_flags 52 0x00057012
f slapstic_bitwise_addr_a 8 0x00057046
f slapstic_bitwise_addr_b 8 0x0005704e
f challenge_target_object_types 28 0x00057056
f character_select_instruction_chain 66 0x00057072
f portrait_display_offsets 8 0x000570b4
f portrait_alpha_words 8 0x000570bc
f portrait_sprite_words 8 0x000570c4
f portrait_alpha_dest_ptrs 16 0x000570cc
f portrait_sprite_dest_ptrs 16 0x000570dc
f joystick_direction_bitmasks 32 0x000570ec
f floor_palette_color_indices 108 0x0005710c
f service_instruction_text_chain 96 0x00057178
f forcefield_delay_alignment 2 0x000571d8
f forcefield_cycle_delay_profiles 32 0x000571da
f forcefield_cycle_delay_ptrs 16 0x000571fa
f secret_player_palette_words 8 0x0005720a
f player_color_name_ptrs 16 0x00057212
f player_color_name_strings 32 0x00057222
f character_name_ptrs 16 0x00057242
f character_name_strings 40 0x00057252
f level_start_message_strings 184 0x0005727a
f dead_header_byte_block 14 0x00057332
f character_hud_text_ptrs 16 0x00057340
f player_text_palette_words 8 0x00057350
f dead_position_word_block 8 0x00057358
f challenge_timer_base 28 0x00057360
f challenge_timer_random_minutes 28 0x0005737c
f challenge_shared_qualifier_text 60 0x00057398
f challenge_qualifier_descs 112 0x000573d4
f challenge_unique_qualifier_text 104 0x00057444
f challenge_it_desc 8 0x000574ac
f challenge_it_text 4 0x000574b4
f character_glyph_rows 102 0x000574b8
f pad_5751e 2 0x0005751e
f ui_status_strings 88 0x00057520
f dip_switch_display_records 192 0x00057578
f continue_screen_header 12 0x00057638
f continue_blank_line 20 0x00057644
f continue_press_start 20 0x00057658
f continue_within_seconds 20 0x0005766c
f continue_game_line 20 0x00057680
f continue_level_line 20 0x00057694
f heartbeat_mask_table 14 0x000576a8
f score_star_picture_cycle 28 0x000576b6
f score_effect_picture_cycle_a 8 0x000576d2
f score_effect_picture_cycle_b 8 0x000576da
f shot_velocity_x 176 0x000576e2
f shot_velocity_y 176 0x00057792
f health_per_coin_table 64 0x00057862
f player_power_palette_handler_ptrs 16 0x00057842
f player_hurt_palette_handler_ptrs 16 0x00057852
f spawn_candidate_column_delta 16 0x000578a2
f spawn_candidate_row_delta 16 0x000578b2
f shot_counter_reload 24 0x000578c2
f random_item_group_ptrs 16 0x000578da
f random_item_group_counts 8 0x000578ea
f score_spin_picture_cycle 24 0x000578f2
f start_game_player_count_sounds 16 0x0005790a
f random_item_group_values 24 0x0005791a
f player_transition_sound_ids 16 0x00057932
f heartbeat_sound_table 16 0x00057942
f player_coin_sound_ids 16 0x00057952
f early_level_speech_choices 12 0x00057962
f later_level_speech_choices 12 0x0005796e
f character_lowhealth_speech 16 0x0005797a
f generator_spawn_object_type 36 0x0005798a
f generator_spawn_vpos_correction 36 0x000579ae
f death_potion_score_table 16 0x000579d2
f death_potion_popup_type_table 16 0x000579e2
f score_popup_picture_table 60 0x000579f2
f monster_contact_damage_table 128 0x00057a2e
f character_hurt_sound_banks 132 0x00057aae
f hurt_speech_cooldown_base 10 0x00057b32
f character_hurt_sound_ptrs 16 0x00057b3c
f character_hurt_sound_counts 4 0x00057b4c
f generator_cell_dx 24 0x00057b50
f generator_cell_dy 24 0x00057b68
f generator_spawn_direction 24 0x00057b80
f monster_shot_spawn_h_offset 16 0x00057b98
f monster_shot_spawn_v_offset 16 0x00057ba8
f lobber_shot_spawn_h_offset 16 0x00057bb8
f lobber_shot_spawn_v_offset 16 0x00057bc8
f dead_tile_word_block 738 0x00057bd8
f factory_highscore_records 320 0x00057eba
f pad_57ffa 6 0x00057ffa
f score_coin_initials_records 112 0x00058000
f invisibility_flash_masks 32 0x00058070
f fighting_anim_end 8 0x00058090
f demo_stream_ptrs 16 0x00058098
f player_speed_normal 16 0x000580a8
f player_anim_rate 16 0x000580b8
f player_collision_size 16 0x000580c8
f player_delta_x 16 0x000580d8
f player_delta_y 16 0x000580e8
f pad_580f8 4 0x000580f8
f joystick_nibble_to_direction 32 0x000580fc
f fight_direction_map 32 0x0005811c
f health_drain_table 32 0x0005813c
f dialog_tip_ptrs 48 0x0005815c
f demo_player0_input_stream 56 0x0005818c
f demo_input_streams 256 0x0005818c
f demo_player1_input_stream 150 0x000581c4
f demo_player2_input_stream 2 0x0005825a
f demo_player3_input_stream 48 0x0005825c
f dialog_tip_records 642 0x0005828c
f pad_5858b 1 0x0005858b
f attract_display_run_ctrl 125 0x0005850e
f mazeobj_hpos_correction_tbl 128 0x0005858c
f mazeobj_vpos_offset_tbl 64 0x0005860c
f mazeobj_hsize_tier_tbl 64 0x0005864c
f mazeobj_base_picture_tbl 128 0x0005868c
f dead_picture_word_block 62 0x0005870c
f anim_table_shooting 256 0x0005874a
f anim_table_fighting 512 0x0005884a
f anim_table_idle 64 0x00058a4a
f anim_table_walking 256 0x00058a8a
f projectile_picture_table 128 0x00058b8a
f anim_tiles_sorcerer 128 0x00058c0a
f thief_escape_anim 16 0x00058c8a
f thief_walk_anim 128 0x00058c9a
f thief_idle_by_direction 16 0x00058d1a
f pad_58d2a 2 0x00058d2a
f thief_walk_anim_compact 64 0x00058d2c
f mugger_walk_anim 128 0x00058d6c
f mugger_idle_by_direction 16 0x00058dec
f pad_58dfc 2 0x00058dfc
f mugger_walk_anim_compact 64 0x00058dfe
f special_projectile_picture_table 160 0x00058e3e
f monster_projectile_picture_table 66 0x00058ede
f invulnerable_food_pictures 6 0x00058f20
f anim_tiles_ghost 128 0x00058f26
f anim_tiles_grunt 128 0x00058fa6
f anim_tiles_grunt_moving 128 0x00059026
f anim_tiles_demon 128 0x000590a6
f anim_tiles_demon_moving 128 0x00059126
f anim_tiles_lobber 128 0x000591a6
f anim_tiles_sorcerer_moving 128 0x00059226
f anim_tiles_death 128 0x000592a6
f anim_tiles_death_moving_view 128 0x000592b6
f anim_tiles_acid 128 0x00059336
f anim_tiles_acid_moving 128 0x000593b6
f anim_tiles_it 128 0x00059436
f anim_tiles_it_special 128 0x000594b6
f anim_tiles_monster_special_attack 128 0x00059536
f anim_tiles_lobber_throw 128 0x000595b6
f anim_tiles_monster_special_state 128 0x00059636
f shot_damage_base_tbl 12 0x000596b6
f shot_damage_rand_tbl 12 0x000596c2
f monstshot_damage_tbl 40 0x000596ce
f speech_charname_tbl 64 0x000596f6
f hint_text_ptrs 80 0x00059736
f hint_text_strings 304 0x00059786
f hint_speech_records 330 0x000598b6
f gameplay_tip_strings 340 0x00059a00
f maze_decomp_type_ptrs 16 0x00059b54
f powerup_bit_masks 24 0x00059b64
f powerup_speech_ids 48 0x00059b7c
f first_encounter_message_records 1620 0x00059bac
f first_encounter_message_ptrs 128 0x0005a200
f first_encounter_speech_ids 128 0x0005a280
f first_encounter_alt_message_ptrs 128 0x0005a300
f powerup_name_strings 384 0x0005a380
f powerup_name_ptrs 64 0x0005a500
f monster_legend_labels 46 0x0005a540
f monster_legend_cells 258 0x0005a56e
f monster_object_name_strings 110 0x0005a670
f legend_powerup_desc_chain 284 0x0005a6de
f legend_object_desc_chain 116 0x0005a7fa
f legend_wallfloor_desc_chain 94 0x0005a86e
f legend_credit_roles_chain 220 0x0005a8cc
f legend_credit_name_strings 192 0x0005a9a8
f legend_credit_names_chain 178 0x0005aa68
f treasure_bonus_coin_label 12 0x0005ab1a
f treasure_bonus_treasure_label 12 0x0005ab26
f treasure_bonus_equals_label 8 0x0005ab32
f treasure_no_bonus_label 12 0x0005ab3a
f treasure_5000_coin_label 18 0x0005ab46
f treasure_no_bonus_label_alt 12 0x0005ab58
f treasure_seconds_speech 44 0x0005ab64
f treasure_fake_countdown_sequences 80 0x0005ab90
f treasure_fake_countdown_ptrs 16 0x0005abe0
f treasure_fakeout_speech 8 0x0005abf0
f treasure_timeout_speech 16 0x0005abf8
f treasure_warning_speech 16 0x0005ac08
f treasure_warning_delay 8 0x0005ac18
f logo_brightness_seq 14 0x0005ac20
f logo_motion_program_full 32 0x0005ac2e
f logo_motion_program_short 16 0x0005ac4e
f fixed_playfield_palette_bank 192 0x0005ac5e
f alpha_palette_init 128 0x0005ad1e
f mob_palette_init 128 0x0005ad9e
f mob_palette_extended 384 0x0005ae1e
f character_palette_ptrs 16 0x0005af9e
f aux_palette_init 128 0x0005afa6
f tport_palette_cycle_blocks 96 0x0005afae
f character_full_palettes 512 0x0005b00e
f player0_hurt_palette_cycle 72 0x0005b20e
f player1_hurt_palette_cycle 72 0x0005b256
f player2_hurt_palette_cycle 72 0x0005b29e
f player3_hurt_palette_cycle 72 0x0005b2e6
f player0_power_palette_cycle 192 0x0005b32e
f player1_power_palette_cycle 192 0x0005b3ee
f player2_power_palette_cycle 192 0x0005b4ae
f player3_power_palette_cycle 192 0x0005b56e
f thief_stealable_power_masks 12 0x0005b62e
f thief_contact_damage 16 0x0005b63a
f direction_column_delta 18 0x0005b64a
f direction_row_delta 18 0x0005b65c
f maze_object_traversability_flags 64 0x0005b66e
f thief_collision_remove_flags 64 0x0005b6ae
f thief_hurt_sound_choices 12 0x0005b6ee
f thief_player_speech_ids 8 0x0005b6fa
f mugger_player_speech_ids 8 0x0005b702
f thief_direction_step_size 18 0x0005b70a
f tport_direction_rotation 8 0x0005b71c
f damage_comment_speech_ids 8 0x0005b724
f character_reflect_timer_init 8 0x0005b72c
f character_stun_delay_add 8 0x0005b734
f tile_effect_sound_ids 8 0x0005b73c
f tile_effect_sound_ids_alt 8 0x0005b744
f pickup_score_values 40 0x0005b74c
f pickup_score_popup_types 20 0x0005b774
f level_exit_sound_ids 16 0x0005b788
f pickup_random_sound_banks 40 0x0005b798
f pickup_random_sound_ptrs 16 0x0005b7c0
f pickup_random_sound_counts 4 0x0005b7d0
f collision_hpos_base_by_case 16 0x0005b7d4
f collision_hpos_random_range_by_player 8 0x0005b7e4
f collision_bonus_threshold_by_case 16 0x0005b7ec
f exit_rotation_offset_by_count 32 0x0005b7fc
f exit_desc_by_floorpattern 1024 0x0005b81c
f logo_outer_timer_init 2 0x0005ba68
f logo_inner_timer_init 2 0x0005ba6a
f logo_bright_min 2 0x0005ba6c
f logo_bright_max 2 0x0005ba6e
f forcefield_gfx_ptrs 64 0x0005ba70
f shot_reflect_hdelta 16 0x0005bab0
f shot_reflect_vdelta 16 0x0005bac0
f shot_reflect_sound_tbl 16 0x0005bad0
f floor_desc_base 256 0x0005bae0
f wall_desc_blocks 3264 0x0005bbe0
f floor_type10_desc 8 0x0005c8a0
f floor_type11_desc 8 0x0005c8a8
f dead_sequential_tile_codes 504 0x0005c8b0
f floor_type3e_descs 128 0x0005caa8
f attract_display_tile_stream 2000 0x0005cb28
f special_object_tile_numbers 504 0x0005cb48
f special_object_anim_tiles 1464 0x0005cd40
f wall_desc_pattern6 216 0x0005d2f8
f wall_desc_destructible 24 0x0005d3d0
f dragon_probe_delta_a 16 0x0005d3e8
f dragon_probe_delta_b 16 0x0005d3f8
f dragon_spawn_offset_a 16 0x0005d408
f dragon_spawn_offset_b 16 0x0005d418
f dragon_facing_offset 16 0x0005d428
f dragon_head_hdelta 64 0x0005d438
f dragon_head_vdelta 64 0x0005d478
f dragon_fire_segment_tbl 16 0x0005d4b8
f dragon_pose_hdelta 32 0x0005d4c8
f dragon_pose_vdelta 32 0x0005d4e8
f dragon_body_pics 32 0x0005d508
f dragon_head_pics 80 0x0005d528
f dragon_path_programs 80 0x0005d578
f playfield_palettes 512 0x0005d5c8
f playfield_special_palette_bank 128 0x0005d7c8
f playfield_special_palette_lowwall_view 96 0x0005d7e8
f palette_color_ramps 416 0x0005d848
f secretcode_text_recs 176 0x0005d9e8
f potion_effect_matrix 448 0x0005da98
f mob_create 1 0x0005dc58
f moblist_insert 1 0x0005dcbc
f moblist_replace 1 0x0005dd72
f moblist_remove 1 0x0005dda8
f moblist_remove_and_clear 1 0x0005ddda
f move_mob_slot 1 0x0005de0a
f moblist_remove_and_clear_regs 1 0x0005de44
f moblist_unlink_regs 1 0x0005ded4
f mob_place_tport_anim 1 0x0005df5a
f mob_place_shot 1 0x0005df68
f mob_place_anim 1 0x0005df72
f exit_create_player_anim 1 0x0005df80
f tport_create_splodey 1 0x0005df8e
f mob_place_explosion 1 0x0005df9c
f insert_mob_depth_sorted 1 0x0005dfa6
f mob_depth_remove 1 0x0005e064
f ray_march_down 1 0x0005e10c
f ray_march_up 1 0x0005e1d8
f ray_march_left 1 0x0005e2a2
f ray_march_right 1 0x0005e35e
f main_walls_random_move 1 0x0005e41a
f pf_stamp_update 1 0x0005e536
f pf_stamp_update_regs 1 0x0005e542
f tile_on_screen_d4 1 0x0005e57e
f tile_on_screen_test 1 0x0005e584
f tile_near_screen_d4 1 0x0005e5d2
f tile_near_screen_test 1 0x0005e5d8
f main_walls_cyclic_move 1 0x0005e62a
f maze_place_object_types 1 0x0005e7a6
f maze_convert_walls_to_exits 1 0x0005e80c
f maze_special_floor 1 0x0005e868
f pf_floor_draw_xy 1 0x0005e888
f pf_floor_update 1 0x0005e892
f maze_floor_decor 1 0x0005ea00
f pf_isblankfloor_stack 1 0x0005ea26
f pf_isblankfloor 1 0x0005ea2e
f pf_is_connectable_floor_xy 1 0x0005ea66
f pf_wall_draw 1 0x0005eab8
f pf_wall_draw_stack 1 0x0005eac2
f wall_pattern_offsets 32 0x0005edd4
f wall_random_desc_ptrs 48 0x0005edf4
f wall_conn_variant_tbl 256 0x0005ee24
f wall_conn_variant_tbl6 256 0x0005ef24
f wall_place_playfield_update 1 0x0005f024
f maze_init_walls 1 0x0005f2c0
f mob_place_tile 1 0x0005f310
f pf_replace 1 0x0005f31e
f refresh_tile_visual_stack 1 0x0005f598
f refresh_tile_visual 1 0x0005f5a0
f refresh_tile_visual_legacy 1 0x0005f644
f pf_isdoor_stack 1 0x0005f772
f pf_isdoor 1 0x0005f77a
f maze_doors_setup 1 0x0005f7c0
f pf_door_update_surrounding_xy 1 0x0005f7f0
f pf_door_update_surrounding 1 0x0005f7fa
f pf_door_draw_xy 1 0x0005f876
f pf_door_draw 1 0x0005f880
f door_gfx_by_neighbors 32 0x0005f9ce
f door_gfx_type2 18 0x0005faca
f door_hpos_sub2 18 0x0005fadc
f door_vpos_add2 18 0x0005faee
f door_gfx_type3 18 0x0005fbdc
f door_vpos_sub3 18 0x0005fbee
f door_vpos_add3 18 0x0005fc00
f player_inventory_vram_ptrs 16 0x0005fc12
f random_seeded 1 0x0005fc22
f random_bound_stack_core 1 0x0005fc26
f random_core 1 0x0005fc2c
f random_word 1 0x0005fc46
f getrandom 1 0x0005fc4e
f pf_isff_d0 1 0x0005fc56
f pf_isff 1 0x0005fc5e
f pf_palette_clear 1 0x0005fcce
f display_state_clear 1 0x0005fd14
f memclear 1 0x0005fd58
f memclear_core 1 0x0005fd64
f copy_longwords 1 0x0005fd6a
f palette_fade_copy 1 0x0005fd80
f supersorc_direction_bias 6 0x0005fdac
f supersorc_probe_steps 6 0x0005fdb2
f supersorc_place_helper 1 0x0005fdb8
f supersorc_place 1 0x0005fde0
f dead_truncated_supersorc_epilogues 26 0x0005ff98
f hw.eeprom 1 0x00802001
f hw.player1_input 1 0x00803001
f hw.player2_input 1 0x00803003
f hw.player3_input 1 0x00803005
f hw.player4_input 1 0x00803007
f hw.vblank_selftest 1 0x00803009
f hw.sound_read 1 0x0080300f
f hw.watchdog 1 0x00803100
f hw.led1 1 0x00803121
f hw.led2 1 0x00803123
f hw.led3 1 0x00803125
f hw.led4 1 0x00803127
f hw.aux_latch 1 0x0080312f
f hw.sound_reset 1 0x0080312f
f hw.vblank_ack 1 0x00803140
f hw.eeprom_unlock 1 0x00803150
f hw.sound_write 1 0x00803171
f vram.playfield 1 0x00900000
f vram.mob_picture 1 0x00902000
f vram.mob_hpos 1 0x00902800
f vram.mob_vpos 1 0x00903000
f vram.mob_link 1 0x00903800
f ram.os_flag 2 0x00904000
f ram.mazenum_current 2 0x00904000
f vram.spare 1 0x00904000
f ram.vblank_semaphore 2 0x00904002
f ram.levelnum_current 2 0x00904004
f ram.pf_vscroll_hi 2 0x00904006
f ram.pf_hscroll 2 0x00904008
f ram.pf_vscroll_lo 2 0x0090400a
f ram.timer_countdown 2 0x0090400c
f ram.sound_data_recv 2 0x0090400e
f ram.sound_data_flag 2 0x00904010
f ram.timer_eepromwrite 4 0x00904012
f ram.game_hook_flag 2 0x00904014
f ram.treas_mazerand_adder 2 0x00904016
f ram.treas_mazerand_num 2 0x00904018
f ram.wallcycle_time 2 0x0090401a
f ram.wallcycle_type 1 0x0090401c
f ram.wallcycle_type_pad 1 0x0090401d
f ram.playfield_colorsave1 2 0x0090401e
f ram.playfield_colorsave2 2 0x00904020
f ram.potion_player 2 0x00904022
f ram.collision_dist_H 2 0x00904024
f ram.collision_dist_V 2 0x00904026
f ram.shothit_dist_H 2 0x00904028
f ram.shothit_dist_V 2 0x0090402a
f ram.palette_pulse_dir_b 2 0x0090402c
f ram.palette_pulse_dir_a 2 0x0090402e
f ram.tport_cycle_pos 2 0x00904030
f ram.tport_cycle_dir 2 0x00904032
f ram.tport_cycle_divider 2 0x00904034
f ram.ptr_playfield_color1 4 0x00904036
f ram.ptr_playfield_color2 4 0x0090403a
f ram.ptr_playfield_color3 4 0x0090403e
f ram.ptr_ff_cycle_delay 4 0x00904042
f ram.forcefield_color 2 0x00904046
f ram.ff_cycle_timer 2 0x00904048
f ram.ff_cycle_index 1 0x00904049
f ram.thief_path_direction 1 0x0090404a
f ram.soundqueue 8 0x0090404b
f ram.soundqueue_head 1 0x00904053
f ram.soundqueue_tail 1 0x00904054
f ram.player_potionsnum 4 0x00904055
f ram.player_keysnum 4 0x0090405a
f ram.monster_cap_bonus 1 0x0090405f
f ram.trick_player 1 0x00904063
f ram.trick_last 1 0x00904064
f ram.trick_tasknum 1 0x00904065
f ram.mob_state_link 2048 0x00904066
f ram.maze_decomp_htype1 2 0x00904866
f ram.maze_decomp_htype2 2 0x00904868
f ram.maze_decomp_vtype1 2 0x0090486a
f ram.maze_decomp_vtype2 2 0x0090486c
f ram.secret_need_hint 2 0x0090486e
f ram.secret_prev_maze 2 0x00904870
f ram.secret_tricks_flags 4 0x00904872
f ram.current_player 2 0x00904876
f ram.secret_possible_counter 2 0x00904878
f ram.secret_possible_start 2 0x0090487a
f ram.dragon_fire_cooldown 2 0x0090487c
f ram.dialog_once_flags 2 0x0090487e
f ram.thief_pursuit_direction 1 0x00904060
f ram.thief_pursuit_player 1 0x00904061
f ram.thief_pursuit_shot_direction 1 0x00904062
f ram.dragon_hits 2 0x00904880
f ram.dragon_head_hpos 2 0x00904882
f ram.dragon_head_vpos 2 0x00904884
f ram.dragon_path_num 2 0x00904886
f ram.dragon_move_state 2 0x0090488c
f ram.dragon_facing 2 0x0090488e
f ram.dragon_state 2 0x00904890
f ram.dragon_anim_ctr 2 0x00904892
f ram.dragon_seg_mob_ids 8 0x00904894
f ram.ptr_exit_openclose_anim 4 0x0090489c
f ram.randwall_low_watermark 2 0x009048a0
f ram.randwall_target 2 0x009048a2
f ram.randwall_current 2 0x009048a4
f ram.randwall_timer 2 0x009048a6
f ram.player_shot_last_wall_pos 8 0x009048a8
f ram.thief_direction_change_pos 2 0x009048b0
f ram.poison_timer 2 0x009048b2
f ram.player_deferred_move_flags 8 0x009048b4
f ram.thief_speed 2 0x009048bc
f ram.reflect_count 8 0x009048be
f ram.escape_timer 2 0x009048c6
f ram.active_mob_ids 24 0x009048c8
f ram.player_powers 8 0x009048e0
f ram.player_character 8 0x009048e8
f ram.player_joystick 8 0x009048f0
f ram.lobber_shot_vec_h 8 0x009048f8
f ram.lobber_shot_vec_v 8 0x00904900
f ram.player_redraw 4 0x00904908
f ram.idle_timer 2 0x0090490c
f ram.player_bonusmult 8 0x0090490e
f ram.frame_overflow 2 0x00904916
f ram.game_mode 2 0x00904918
f ram.attract_legend 2 0x0090491a
f ram.level_flags 4 0x0090491c
f ram.level_flags_2 1 0x0090491d
f ram.level_flags_3 1 0x0090491e
f ram.level_flags_4 1 0x0090491f
f ram.player_input_raw 8 0x00904920
f ram.level_players_active 2 0x00904928
f ram.shot_timer_next 16 0x0090492a
f ram.score_display_timer 8 0x0090493a
f ram.mob_depth_key 64 0x00904940
f ram.mob_effect_anim_counter 4 0x0090497c
f ram.player_health 16 0x00904980
f ram.player_score 16 0x00904990
f ram.player_status 4 0x009049a0
f ram.player_facing_dir 8 0x009049a4
f ram.player_fighting_dir 8 0x009049ac
f ram.player_shooting 8 0x009049b4
f ram.player_anim_counter 8 0x009049bc
f ram.shot_direction 24 0x009049c4
f ram.it_player 2 0x009049dc
f ram.mob_depth_list_head 2 0x009049de
f ram.maze_player_start_slot 2 0x009049e0
f ram.two_player_mode 2 0x009049e2
f ram.dialog_first_encounter_flags 4 0x009049e4
f ram.treasure_timer 2 0x009049e8
f ram.last_coin_state 4 0x009049ea
f ram.speech_counter 2 0x009049ee
f ram.sound_queue_state 2 0x009049f0
f ram.sound_idle_timer 2 0x009049f2
f ram.sound_cpu_retry_count 2 0x009049f4
f ram.player_hurt_palette_offset 8 0x009049f6
f ram.player_power_palette_offset 8 0x009049fe
f ram.exit_count 2 0x00904a06
f ram.exit_timer 2 0x00904a08
f ram.exit_open_id 2 0x00904a0a
f ram.exit_close_id 2 0x00904a0c
f ram.movement_blocked 2 0x00904a0e
f ram.logo_scroll_ptr 4 0x00904a10
f ram.logo_scroll_timer 2 0x00904a14
f ram.logo_color_dir 2 0x00904a16
f ram.logo_cycle_timer 2 0x00904a18
f ram.logo_bright_timer 2 0x00904a1a
f ram.logo_bright_accum 2 0x00904a1c
f ram.logo_color_cur 2 0x00904a1e
f ram.logo_anim_ptr 4 0x00904a20
f ram.game_settings 2 0x00904a24
f ram.player_state_timer 8 0x00904a26
f ram.name_entry_scroll_velocity 8 0x00904a2e
f ram.name_entry_repeat_delay 4 0x00904a36
f ram.player_initials_buf 16 0x00904a3a
f ram.player_highscore_rank 4 0x00904a4a
f ram.global_ui_delay_timer 2 0x00904a4e
f ram.player_treascount 4 0x00904a50
f ram.player_stundelay 8 0x00904a54
f ram.death_hits 2 0x00904a5c
f ram.unused_init_word_904a5e 2 0x00904a5e
f ram.monster_iter_ptr 2 0x00904a60
f ram.monster_cull_h_origin 2 0x00904a62
f ram.monster_cull_v_origin 2 0x00904a64
f ram.lobber_shot_h_accum 8 0x00904a66
f ram.lobber_shot_v_accum 8 0x00904a6e
f ram.door_endpoint_pos 16 0x00904a76
f ram.door_endpoint_dir 16 0x00904a86
f ram.ptr_dialog_pos 4 0x00904a96
f ram.dialog_dim_H 2 0x00904a9a
f ram.dialog_dim_V 2 0x00904a9c
f ram.dialog_timer 2 0x00904a9e
f ram.ptr_dialog_box_x 2 0x00904aa0
f ram.ptr_dialog_box_y 2 0x00904aa2
f ram.dialog_msg_buf 30 0x00904aa4
f ram.scroll_hpos_origin 2 0x00904ac2
f ram.scroll_vpos_origin 2 0x00904ac4
f ram.welcome_elapsed_frames 4 0x00904ac6
f ram.player_lowhealth_spoken 4 0x00904aca
f ram.player_respawn_speech_timer 8 0x00904ace
f ram.player_pending_damage 8 0x00904ad6
f ram.player_damage_total 8 0x00904ade
f ram.player_damage_sample_timer 8 0x00904ae6
f ram.player_damage_sample_count 8 0x00904aee
f ram.player_eatcount 4 0x00904af6
f ram.hurt_speech_timer 8 0x00904afa
f ram.shot_anim_lifetime_counter 24 0x00904b02
f ram.player_scorepercoin 16 0x00904b1a
f ram.player_coincount 8 0x00904b2a
f ram.player_onlevel 8 0x00904b32
f ram.player_death_damage_counter 8 0x00904b3a
f ram.death_touch_timer 8 0x00904b42
f ram.ff_hurt_timer 8 0x00904b4a
f ram.level_next 2 0x00904b52
f ram.maze_next 2 0x00904b54
f ram.special_bonus_score 2 0x00904b56
f ram.playfield_palette_index 2 0x00904b58
f ram.playfield_special_variant 2 0x00904b5a
f ram.floorpattern 2 0x00904b5c
f ram.wallpattern 2 0x00904b5e
f ram.attract_count 2 0x00904b60
f ram.demo_ptr 16 0x00904b66
f ram.demo_timer 4 0x00904b76
f ram.monster_generation_retry_timer 2 0x00904b7a
f ram.attract_timer 2 0x00904b7c
f ram.level_next_potion 2 0x00904b7e
f ram.level_next_treasure 2 0x00904b80
f ram.title_intro_state 2 0x00904b82
f ram.level_tport_count 2 0x00904b84
f ram.games_played_counter 2 0x00904b86
f ram.ptr_maze_data 4 0x00904b88
f ram.maze_slapstic_cmd_offset 2 0x00904b8c
f ram.eeprom_cache_stat1 1 0x00904b8e
f ram.eeprom_cache_stat2 1 0x00904b8f
f ram.eeprom_cache_stat3 1 0x00904b90
f ram.eeprom_cache_stat4 1 0x00904b91
f ram.eeprom_cache_stats 2 0x00904b92
f ram.eeprom_cache_settings 2 0x00904b94
f ram.thief_victim_pos 2 0x00904b98
f ram.thief_victim 2 0x00904b9a
f ram.thief_direction 2 0x00904b9c
f ram.thief_enter_time 2 0x00904b9e
f ram.thief_mode 2 0x00904ba0
f ram.thief_previous_pos 2 0x00904ba2
f ram.thief_current_pos 2 0x00904ba4
f ram.thief_next_pos 2 0x00904ba6
f ram.mugger_item_nextlevel 4 0x00904ba8
f ram.thief_item_nextlevel 4 0x00904bac
f ram.mugger_item_carried 4 0x00904bb0
f ram.thief_item_carried 4 0x00904bb4
f ram.thief_collision_direction_code 2 0x00904bb8
f ram.thief_start_location 2 0x00904bba
f ram.thief_stolen_item 2 0x00904bbc
f ram.thief_tport_active 2 0x00904bbe
f ram.treasure_announcement_delay 2 0x00904bc0
f ram.treasure_voice_set 2 0x00904bc2
f ram.tport_saved_picture 8 0x00904bc4
f ram.tport_saved_mob_state 2 0x00904bcc
f ram.player_tport_phase 8 0x00904bce
f ram.tport_frame_counter 2 0x00904bd6
f ram.player_tile_or_tport_dest 8 0x00904bd8
f ram.tport_transition_mob 2 0x00904be0
f ram.player_tport_type 8 0x00904be2
f ram.player_tport_route_state 8 0x00904bea
f ram.movement_type 2 0x00904bf2
f ram.unused_gap_904bf4 8 0x00904bf4
f ram.random_seed 2 0x00904bfc
f ram.vblank_abort_guard 2 0x00904c00
f ram.player_hurt_palette_stubs 24 0x00905f00
f ram.player_power_palette_stubs 24 0x00905f18
f ram.fullscreen_scroll_active 1 0x00904f02
f ram.fullscreen_scroll_offset 1 0x00904f06
f ram.os_vblank_active 1 0x00904f0c
f ram.display_mode 1 0x00904f0e
f ram.text_effect_slots 1 0x00904f18
f ram.input_source_ptr 1 0x00904f8a
f ram.sound_queue 1 0x00904f8e
f ram.eeprom_work 1 0x00904fa8
f ram.eeprom_error_count 1 0x00904fc0
f ram.coin_counters 1 0x00904fec
f ram.coin_totals 1 0x00904ff0
f ram.coin_pending 1 0x00904ff4
f ram.vblank_counter 1 0x00904ff8
f ram.eeprom_init_timeout_counter_byte 1 0x00904ffa
f ram.eeprom_config_ptr 1 0x00904ffc
f vram.alpha 2048 0x00905000
f ram.hud_mob_table 3072 0x00905048
f ram.path_direction_grid 3072 0x00905054
f ram.tport_route_forward 256 0x00905c54
f ram.tport_route_reverse 256 0x00905d54
f ram.hurt_cooldown 8 0x00905f30
f ram.reflect_timer 8 0x00905f38
f ram.acid_timer 8 0x00905f40
f ram.stun_timer 8 0x00905f48
f ram.invis_timer 8 0x00905f50
f ram.debounce_shift_a 8 0x00905f58
f ram.debounce_shift_b 8 0x00905f60
f ram.player_supershot 4 0x00905f68
f ram.secret_saved_supershot 1 0x00905f6d
f vram.pf_vscroll_reg 2 0x00905f6e
f ram.priority_bucket_heads 2 0x00905f80
f ram.priority_bucket_heads_tail 128 0x00905f82
f vram.color_alpha 1 0x00910000
f vram.color_mob 1 0x00910200
f vram.color_ram_mob_pal 2 0x00910204
f vram.color_ram_logo_bright 2 0x00910332
f vram.color_pf_shadow 1 0x00910400
f vram.color_pf 1 0x00910500
f vram.color_spare 1 0x00910600
f ram.tport_pos_table 64 0x00910700
f ram.ff_segment_table 128 0x00910780
f vram.pf_hscroll_reg 1 0x00930000
f osdata.working_ram_error_text 18 0x00000c86
f osdata.rom_error_descriptor_pointer_tables 98 0x00000f1c
f osdata.number_format_bit_masks 22 0x00002a48
f osdata.text_effect_dispatch_offsets 12 0x00002c16
f osdata.large_character_tile_quads 208 0x000033d2
f osdata.large_character_clear_maps 128 0x000034a2
f osdata.eeprom_redundancy_probe_order 12 0x000044be
f osdata.eeprom_bit_index_map 16 0x00004736
f osdata.motion_test_lookup_tables 128 0x0000599a
f osdata.diagnostic_pointer_and_endpoint_tables 48 0x00005a1a
f osdata.selftest_descriptor_and_string_stream 1738 0x00005a4a
f osdata.color_name_pointer_table 32 0x00006114
f osdata.display_test_selection_tables 64 0x00006134
f osdata.display_test_palette_words 16 0x00006174
f osdata.color_test_palette_source_prefix 1184 0x00006184
f osdata.palette_and_rom_error_descriptor_overlap 352 0x00006624
f osdata.rom_error_descriptor_stream 514 0x00006784
f osdata.coin_counter_decode_table 8 0x00006986
f osdata.game_config_descriptor_table 26 0x0000698e
f osdata.session_difficulty_factors 4 0x000069a8
f osdata.statistics_prompt_strings 154 0x000069ac
f osdata.statistics_summary_table 210 0x00006a46
f osdata.statistics_error_and_navigation_descriptors 78 0x00006b18
f osdata.operator_more_marker_variants 36 0x00006b66
f osdata.operator_ui_palette 16 0x00006b8a
f osdata.operator_option_descriptor_stream 416 0x00006b9a
f osdata.built_in_coin_option_stream 110 0x00006d3a
f legacydata.object_motion_tables 246 0x0000860c
f legacydata.direction_route_tables 132 0x00008a64
f legacydata.mob_bucket_tables 152 0x00008b9e
f legacydata.path_probe_tables 434 0x00008d86
f legacydata.recursive_move_tables 50 0x00009252
f legacydata.game_option_stream 456 0x00009a10
f legacydata.level_display_tables 324 0x00009bd8
f legacydata.status_text_descriptors 772 0x00009d1c
f legacydata.gameplay_numeric_tables_a 7452 0x0000a020
f legacydata.factory_high_scores 320 0x0000bd3c
f legacydata.high_score_text 122 0x0000be7c
f legacydata.name_entry_and_gameplay_tables 586 0x0000bef6
f legacydata.tutorial_descriptor_stream 656 0x0000c140
f legacydata.gameplay_numeric_tables_b 4250 0x0000c3d0
f legacydata.hint_and_legend_stream 3100 0x0000d46a
f legacydata.legend_and_credit_text 970 0x0000e086
f legacydata.descriptor_and_tile_tables 3312 0x0000e450
f legacydata.palette_and_graphics_tables 2234 0x0000f140
f hw.input_word_array 8 0x00803000
f hw.sound_response_word 2 0x0080300e
f hw.board_enable_latch 2 0x00803120
f hw.sound_reset_control 2 0x0080312e
f hw.sound_command_word 2 0x00803170
f vram.playfield_last_word 2 0x00901ffe
f vram.mob_last_word 2 0x00903ffe
f ram.os_vblank_occurred 2 0x00904004
f ram.sound_test_status_value 2 0x00904012
f ram.selftest_button0_label 26 0x0090403e
f ram.selftest_button1_label 26 0x00904058
f ram.selftest_joystick_label 26 0x00904072
f ram.motion_test_object_index 2 0x0090408c
f ram.motion_test_pattern 2 0x0090408e
f ram.text_repeat_bias 2 0x00904f00
f ram.vblank_sync 2 0x00904f04
f ram.fullscreen_scroll_interval 2 0x00904f0a
f ram.highscore_work_buffer 7 0x00904f44
f ram.active_player_time_mask 1 0x00904f4b
f ram.player_time_last_vblank 4 0x00904f4c
f ram.operator_cursor0 1 0x00904f78
f ram.operator_cursor1 1 0x00904f79
f ram.input_previous_raw 8 0x00904f7a
f ram.input_debounced 8 0x00904f82
f ram.sound_status_poll_busy_count 1 0x00904feb
f vram.spare_last_word 2 0x00904ffe
f vram.alpha_color_test_bottom_row 74 0x00905e80
f vram.alpha_last_word 2 0x00905ffe
f diag.working_ram_error_text 34 0x00906d00
f vram.color_alpha_entry1 2 0x00910002
f vram.color_alpha_entry2 2 0x00910004
f vram.color_alpha_entry3 2 0x00910006
f vram.color_alpha_entry4 2 0x00910008
f vram.color_alpha_entry5 2 0x0091000a
f vram.color_alpha_entry6 2 0x0091000c
f vram.color_alpha_entry7 2 0x0091000e
f vram.color_pf_entry15 2 0x0091051e
f vram.color_last_word 2 0x009107fe
fs *
s 0x040000
