#!/usr/bin/env python3
"""Generate a small radare2 loader from the symbols in gauntlet.r2."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


SETTINGS = (
    "e io.va=true",
    "e anal.arch=m68k",
    "e asm.arch=m68k",
    "e asm.cpu=68010",
    "e asm.bits=32",
    "e cfg.bigendian=true",
)
MAPS = (
    "o row9.bin 0x000000 r-x",
    "o row10.bin 0x038000 r-x",
    "o row76.bin 0x040000 r-x",
)
CANONICAL_OS_NAMES = {
    0x3F68: "rank_high_score",
    0x41C8: "send_sound_command_wait",
    0x41CC: "try_send_sound_command",
}
CANONICAL_FLAG_NAMES = {
    0x579E2: "death_potion_popup_type_table",
    0x904B3A: "ram.player_death_damage_counter",
    0x905F80: "ram.priority_bucket_heads",
    0x905F82: "ram.priority_bucket_heads_tail",
    0x905F6D: "ram.secret_saved_supershot",
}


def canonicalize_function(line: str, canonical_names: dict[int, str]) -> str:
    match = re.match(r"af\+ (0x[0-9A-Fa-f]+) \S+", line)
    if not match:
        return line
    address = int(match.group(1), 16)
    name = canonical_names.get(address)
    return f"af+ 0x{address:x} {name}" if name else line


def canonicalize_flag(line: str, canonical_names: dict[int, str]) -> str:
    match = re.match(r"f \S+ (\S+) (0x[0-9A-Fa-f]+)$", line)
    if not match:
        return line
    address = int(match.group(2), 16)
    name = canonical_names.get(address)
    return f"f {name} {match.group(1)} 0x{address:08x}" if name else line


def documented_game_function_map(function_index: str) -> dict[int, str]:
    # Stop after the first backticked name, not after the whole cell: many
    # canonical rows contain slash-separated aliases in the same cell.
    row = re.compile(r"^\| 0x([0-9A-Fa-f]+) \| `([^`]+)`", re.MULTILINE)
    by_address: dict[int, str] = {}
    for address_text, name in row.findall(function_index):
        address = int(address_text, 16)
        if 0x40000 <= address <= 0x5FFFF:
            by_address.setdefault(address, name)
    return by_address


def generated_text(source: str, function_index: str) -> str:
    game_functions = documented_game_function_map(function_index)
    canonical_names = {**CANONICAL_OS_NAMES, **game_functions}
    function_block = source.split("# functions\n", 1)[1].split("# registers\n", 1)[0]
    functions = [
        canonicalize_function(line, canonical_names)
        for line in function_block.splitlines()
        if line.startswith("af+")
    ]
    functions.extend(
        f"af+ 0x{address:05x} {name}"
        for address, name in sorted(game_functions.items())
    )

    flag_block = source.split("# flags\n", 1)[1].split("# meta\n", 1)[0]
    # The export begins with an obsolete ARM register namespace. Start at the
    # real function namespace, then retain every named symbol in later spaces.
    flag_block = flag_block.split("fs functions\n", 1)[1]
    flags = [
        canonicalize_flag(line[1:], {**canonical_names, **CANONICAL_FLAG_NAMES})
        for line in flag_block.splitlines()
        if line.startswith("'f ")
    ]

    lines = [
        "# Generated by doc/generate_r2_loader.py; do not edit by hand.",
        *MAPS,
        # Opening a raw file resets some decoding settings in r2 6.1.8.
        *SETTINGS,
        "fs functions",
        *functions,
        *flags,
        "fs *",
        "s 0x040000",
        "",
    ]
    return "\n".join(lines)


def runtime_check(root: Path, expected_function_count: int) -> None:
    command = [
        "r2", "-q", "-n", "-e", "scr.color=0",
        "-c", ". doc/gauntlet_loader.r2",
        "-c", "e asm.arch; e asm.cpu; e asm.bits; e cfg.bigendian; oj; om; f~m2mainloop; aflc",
        "-c", "q", "malloc://1",
    ]
    result = subprocess.run(command, cwd=root, text=True, capture_output=True)
    combined = result.stdout + result.stderr
    bad = re.search(r"(?im)^(?:ERROR|FATAL|Invalid|Cannot|Unknown).*", combined)
    if result.returncode or bad:
        raise SystemExit(
            "radare2 loader regression failed:\n" + (bad.group(0) if bad else combined)
        )
    required = (
        "m68k", "68010", "32", "true", "row9.bin", "row10.bin",
        "row76.bin", "m2mainloop", "r-x",
    )
    missing = [item for item in required if item not in combined]
    if missing:
        raise SystemExit(f"radare2 loader output missing: {', '.join(missing)}\n{combined}")
    if not re.search(rf"(?m)^{expected_function_count}$", combined):
        raise SystemExit(
            f"radare2 loader did not create {expected_function_count} analysis functions\n{combined}"
        )
    print(
        "gauntlet_loader.r2: zero-error load; 3 ROM maps; "
        f"m68k/68010/32-bit/big-endian; {expected_function_count} functions"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--run-check", action="store_true")
    args = parser.parse_args()

    here = Path(__file__).resolve().parent
    root = here.parent
    output = here / "gauntlet_loader.r2"
    legacy = (root / "gauntlet.r2").read_text()
    function_index = (here / "07_function_index.md").read_text()
    expected = generated_text(legacy, function_index)
    expected_function_count = len(re.findall(r"(?m)^af\+ ", expected))
    if args.check:
        if output.read_text() != expected:
            raise SystemExit("gauntlet_loader.r2 is stale; regenerate it")
        print("gauntlet_loader.r2: generated content is current")
    else:
        output.write_text(expected)
        print(f"wrote {output}")
    if args.run_check:
        runtime_check(root, expected_function_count)


if __name__ == "__main__":
    main()
